[package]
name = "tinify-aw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinify-rs = "1.1.0"
rexiv2 = "0.9.1"
walkdir = "2"